/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/blender_sat.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null} scale={[5, 5, 5]}>
      <group name="Armature" scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[0, 0, -1.53]} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 1]}>
          <group position={[20.71, -8.84, -119.53]} rotation={[-1.74, -0.23, 2.71]} scale={[1, 1, 1]}>
            <group position={[-6.9, 12.86, 1.65]} rotation={[1.45, 1.2, -3.09]} scale={[1, 1, 1]}>
              <group position={[0, 11.35, 0]} rotation={[Math.PI, 0.47, -Math.PI]} scale={[1, 1, 1]}>
                <group position={[5.14, 40.39, 29.08]} rotation={[0, -0.44, 0]} scale={[1, 1, 1]}>
                  <mesh
                    geometry={nodes.Cube.geometry}
                    material={materials.RootNode_0_}
                    position={[0.45, -70.4, -24.16]}
                    rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  />
                </group>
                <group position={[5.14, 40.39, 29.08]} rotation={[0, -0.44, 0]} scale={[1, 1, 1]}>
                  <mesh
                    geometry={nodes.Cube_2.geometry}
                    material={materials.RootNode_1_}
                    position={[0.45, -33.31, -24.16]}
                    rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  />
                </group>
              </group>
              <group position={[0, 11.35, 0]} rotation={[-Math.PI, 0.11, -Math.PI]} scale={[1, 1, 1]}>
                <group position={[5.14, 40.39, 29.08]} rotation={[0, -0.44, 0]} scale={[1, 1, 1]}>
                  <mesh
                    geometry={nodes.Cube_3.geometry}
                    material={materials.RootNode_2_}
                    position={[0.45, -70.4, -24.16]}
                    rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  />
                </group>
                <group position={[5.14, 40.39, 29.08]} rotation={[0, -0.44, 0]} scale={[1, 1, 1]}>
                  <mesh
                    geometry={nodes.Cube_4.geometry}
                    material={materials.RootNode_3_}
                    position={[0.45, -33.31, -24.16]}
                    rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  />
                </group>
              </group>
              <group position={[0, 11.35, 0]} rotation={[-Math.PI, -0.2, -Math.PI]} scale={[1, 1, 1]}>
                <group position={[5.14, 40.39, 29.08]} rotation={[0, -0.44, 0]} scale={[1, 1, 1]}>
                  <mesh
                    geometry={nodes.Cube_5.geometry}
                    material={materials.RootNode_4_}
                    position={[0.45, -70.4, -24.16]}
                    rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  />
                </group>
                <group position={[5.14, 40.39, 29.08]} rotation={[0, -0.44, 0]} scale={[1, 1, 1]}>
                  <mesh
                    geometry={nodes.Cube_6.geometry}
                    material={materials.RootNode_5_}
                    position={[0.45, -33.31, -24.16]}
                    rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  />
                </group>
              </group>
              <group position={[0, 11.35, 0]} rotation={[-Math.PI, -1.02, -Math.PI]} scale={[1, 1, 1]}>
                <group position={[5.14, 40.39, 29.08]} rotation={[0, -0.44, 0]} scale={[1, 1, 1]}>
                  <mesh
                    geometry={nodes.Cube_7.geometry}
                    material={materials.RootNode_6_}
                    position={[0.45, -70.4, -24.16]}
                    rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  />
                </group>
                <group position={[5.14, 40.39, 29.08]} rotation={[0, -0.44, 0]} scale={[1, 1, 1]}>
                  <mesh
                    geometry={nodes.Cube_8.geometry}
                    material={materials.RootNode_7_}
                    position={[0.45, -33.31, -24.16]}
                    rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  />
                </group>
              </group>
              <group position={[0, 11.35, 0]} rotation={[Math.PI, -0.54, Math.PI]}>
                <group position={[5.14, 40.39, 29.08]} rotation={[0, -0.44, 0]} scale={[1, 1, 1]}>
                  <mesh
                    geometry={nodes.Cube_9.geometry}
                    material={materials.RootNode_8_}
                    position={[0.45, -70.4, -24.16]}
                    rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  />
                </group>
                <group position={[5.14, 40.39, 29.08]} rotation={[0, -0.44, 0]} scale={[1, 1, 1]}>
                  <mesh
                    geometry={nodes.Cube_10.geometry}
                    material={materials.RootNode_9_}
                    position={[0.45, -33.31, -24.16]}
                    rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  />
                </group>
              </group>
              <group position={[0, 11.51, 0]} rotation={[0, -0.88, 0]} scale={[1, 1, 1]}>
                <group position={[-1.31, -7.74, 16.54]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[1, 1, 1]}>
                  <mesh
                    geometry={nodes.Cube_11_1.geometry}
                    material={materials.RootNode_10_}
                    position={[0, 0, 0]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                  <mesh
                    geometry={nodes.Cylindre.geometry}
                    material={materials.RootNode_11_}
                    position={[-0.11, 0.04, 1.61]}
                    rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  />
                  <mesh
                    geometry={nodes.Cylindre_2.geometry}
                    material={materials.RootNode_12_}
                    position={[-0.11, 0.04, -2.23]}
                    rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  />
                </group>
              </group>
              <group position={[0, 11.51, 0]} rotation={[0, -1.39, 0]} scale={[1, 1, 1]}>
                <group position={[-1.31, -7.74, 16.54]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[1, 1, 1]}>
                  <mesh
                    geometry={nodes.Cube_12_1.geometry}
                    material={materials.RootNode_13_}
                    position={[0, 0, 0]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                  <mesh
                    geometry={nodes.Cylindre_3.geometry}
                    material={materials.RootNode_14_}
                    position={[-0.11, 0.04, 1.61]}
                    rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  />
                  <mesh
                    geometry={nodes.Cylindre_4.geometry}
                    material={materials.RootNode_15_}
                    position={[-0.11, 0.04, -2.23]}
                    rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  />
                </group>
              </group>
              <group position={[0, 11.35, 0]} rotation={[0, -0.34, 0]} scale={[1, 1, 1]}>
                <group position={[-12.97, 3.33, -10.53]} rotation={[-Math.PI, 0.7, Math.PI]} scale={[1, 1, 1]}>
                  <mesh
                    geometry={nodes.Cube_13.geometry}
                    material={materials.RootNode_16_}
                    position={[0, -2.42, 0]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                  <mesh
                    geometry={nodes.Cube_14.geometry}
                    material={materials.RootNode_17_}
                    position={[0, 0, 0]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                </group>
              </group>
              <group position={[0, 11.35, 0]} rotation={[0, 1.3, 0]} scale={[1, 1, 1]}>
                <group position={[-12.97, 3.33, -10.53]} rotation={[Math.PI, 0.7, Math.PI]} scale={[1, 1, 1]}>
                  <mesh
                    geometry={nodes.Cube_15.geometry}
                    material={materials.RootNode_18_}
                    position={[0, -27.44, 0]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                  <mesh
                    geometry={nodes.Cube_16.geometry}
                    material={materials.RootNode_19_}
                    position={[0, 0, 0]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                </group>
              </group>
              <group position={[0, 11.35, 0]} rotation={[0, 0.38, 0]} scale={[1, 1, 1]}>
                <group position={[-16.95, -20.29, -5.14]} rotation={[0, -0.44, 0]} scale={[1, 1, 1]}>
                  <mesh
                    geometry={nodes.Cube_17_1.geometry}
                    material={materials.RootNode_20_}
                    position={[0, 0, 0]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                  <mesh
                    geometry={nodes.Molette.geometry}
                    material={materials.RootNode_21_}
                    position={[-2.03, -0.62, 0.08]}
                    rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  />
                </group>
                <group position={[-16.95, 2.85, -5.14]} rotation={[0, -0.44, 0]} scale={[1, 1, 1]}>
                  <mesh
                    geometry={nodes.Cube_18_1.geometry}
                    material={materials.RootNode_22_}
                    position={[0, 0, 0]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                  <mesh
                    geometry={nodes.Molette_2.geometry}
                    material={materials.RootNode_23_}
                    position={[-2.03, -0.62, 0.08]}
                    rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                  />
                </group>
              </group>
              <group position={[0, 0, 0]} rotation={[Math.PI, -0.04, -Math.PI]} scale={[1, 1, 1]}>
                <group position={[74.06, 106.14, -76.28]} rotation={[0, -0.44, -Math.PI / 2]} scale={[1, 1, 1]}>
                  <mesh
                    geometry={nodes.Cylindre_5.geometry}
                    material={materials.RootNode_24_}
                    position={[115.06, -17.5, 103.83]}
                    rotation={[1.79, 0, 0]}
                  />
                </group>
              </group>
              <group position={[0, 0.62, 0]} rotation={[-Math.PI, 1.37, Math.PI]}>
                <group position={[507.76, -223.68, -631.93]} rotation={[0, -0.01, 0]} scale={[1, 1, 1]}>
                  <mesh
                    geometry={nodes.Cylinder_2.geometry}
                    material={materials.RootNode_26_}
                    position={[-502.42, 237.36, 636.19]}
                    rotation={[0, 1.15, 0]}
                  />
                </group>
                <mesh
                  geometry={nodes.Cylinder_1.geometry}
                  material={materials.RootNode_25_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
              </group>
              <group position={[0, -16.58, 0]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
                <mesh
                  geometry={nodes.Cylinder_3.geometry}
                  material={materials.RootNode_28_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.Torus_1.geometry}
                  material={materials.RootNode_27_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
              </group>
              <group position={[0, 17, 0]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
                <mesh
                  geometry={nodes.Cylinder_4.geometry}
                  material={materials.RootNode_30_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.Torus_2_1.geometry}
                  material={materials.RootNode_29_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
              </group>
            </group>
            <group position={[-11.26, 28.47, -4.29]} rotation={[3.07, 0.02, 2.99]} scale={[1, 1, 1]}>
              <group position={[-4.28, 0.58, -8.58]} rotation={[-1.58, 0.03, -1.57]} scale={[1, 1, 1]}>
                <group position={[-9.93, 0, 0]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
                  <group position={[27.29, -0.25, -0.28]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
                    <mesh
                      geometry={nodes.Cap_1.geometry}
                      material={materials.RootNode_33_}
                      position={[0, 0, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                    <mesh
                      geometry={nodes.Rounding_1_1.geometry}
                      material={materials.RootNode_32_}
                      position={[0, 0, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                  </group>
                  <group position={[27.29, -0.25, -0.28]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
                    <mesh
                      geometry={nodes.Cap_2.geometry}
                      material={materials.RootNode_35_}
                      position={[0, 0, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                    <mesh
                      geometry={nodes.Rounding_2_1.geometry}
                      material={materials.RootNode_34_}
                      position={[0, 0, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                  </group>
                  <mesh
                    geometry={nodes.Extrude_NURBS_4_1.geometry}
                    material={materials.RootNode_31_}
                    position={[0, 0, 0]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                </group>
                <group position={[-9.93, 0, 0]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
                  <group position={[8.77, -0.25, -0.28]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
                    <mesh
                      geometry={nodes.Cap_1_2.geometry}
                      material={materials.RootNode_38_}
                      position={[0, 0, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                    <mesh
                      geometry={nodes.Rounding_1_2_1.geometry}
                      material={materials.RootNode_37_}
                      position={[0, 0, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                  </group>
                  <group position={[8.77, -0.25, -0.28]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
                    <mesh
                      geometry={nodes.Cap_2_2.geometry}
                      material={materials.RootNode_40_}
                      position={[0, 0, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                    <mesh
                      geometry={nodes.Rounding_2_2_1.geometry}
                      material={materials.RootNode_39_}
                      position={[0, 0, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                  </group>
                  <mesh
                    geometry={nodes.Extrude_NURBS_5_1.geometry}
                    material={materials.RootNode_36_}
                    position={[0, 0, 0]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                </group>
                <group position={[-9.93, 0, 0]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
                  <group position={[27.29, 5.14, -0.09]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
                    <mesh
                      geometry={nodes.Cap_1_3.geometry}
                      material={materials.RootNode_43_}
                      position={[0, 0, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                    <mesh
                      geometry={nodes.Rounding_1_3_1.geometry}
                      material={materials.RootNode_42_}
                      position={[0, 0, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                  </group>
                  <group position={[27.29, 5.14, -0.09]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
                    <mesh
                      geometry={nodes.Cap_2_3.geometry}
                      material={materials.RootNode_45_}
                      position={[0, 0, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                    <mesh
                      geometry={nodes.Rounding_2_3_1.geometry}
                      material={materials.RootNode_44_}
                      position={[0, 0, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                  </group>
                  <mesh
                    geometry={nodes.Extrude_NURBS_3_1.geometry}
                    material={materials.RootNode_41_}
                    position={[0, 0, 0]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                </group>
                <group position={[-9.93, 0, 0]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
                  <group position={[8.77, 5.14, -0.09]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
                    <mesh
                      geometry={nodes.Cap_1_4.geometry}
                      material={materials.RootNode_48_}
                      position={[0, 0, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                    <mesh
                      geometry={nodes.Rounding_1_4_1.geometry}
                      material={materials.RootNode_47_}
                      position={[0, 0, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                  </group>
                  <group position={[8.77, 5.14, -0.09]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
                    <mesh
                      geometry={nodes.Cap_2_4.geometry}
                      material={materials.RootNode_50_}
                      position={[0, 0, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                    <mesh
                      geometry={nodes.Rounding_2_4_1.geometry}
                      material={materials.RootNode_49_}
                      position={[0, 0, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                  </group>
                  <mesh
                    geometry={nodes.Extrude_NURBS_2_1.geometry}
                    material={materials.RootNode_46_}
                    position={[0, 0, 0]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                </group>
                <group position={[0, 0.83, 0]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
                  <group position={[5.92, 1.7, 0]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
                    <mesh
                      geometry={nodes.Cap_1_5.geometry}
                      material={materials.RootNode_53_}
                      position={[0, 0, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                    <mesh
                      geometry={nodes.Rounding_1_5_1.geometry}
                      material={materials.RootNode_52_}
                      position={[0, 0, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                  </group>
                  <group position={[5.92, 1.7, 0]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
                    <mesh
                      geometry={nodes.Cap_2_5.geometry}
                      material={materials.RootNode_55_}
                      position={[0, 0, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                    <mesh
                      geometry={nodes.Rounding_2_5_1.geometry}
                      material={materials.RootNode_54_}
                      position={[0, 0, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                  </group>
                  <mesh
                    geometry={nodes.Extrude_NURBS_1_1.geometry}
                    material={materials.RootNode_51_}
                    position={[0, 0, 0]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                </group>
                <group position={[0, 1.61, 0.27]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
                  <group position={[2.64, 1.46, 0]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
                    <mesh
                      geometry={nodes.Cap_1_6.geometry}
                      material={materials.RootNode_58_}
                      position={[0, 0, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                    <mesh
                      geometry={nodes.Rounding_1_6_1.geometry}
                      material={materials.RootNode_57_}
                      position={[0, 0, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                  </group>
                  <group position={[2.64, 1.46, 0]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
                    <mesh
                      geometry={nodes.Cap_2_6.geometry}
                      material={materials.RootNode_60_}
                      position={[0, 0, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                    <mesh
                      geometry={nodes.Rounding_2_6_1.geometry}
                      material={materials.RootNode_59_}
                      position={[0, 0, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                  </group>
                  <mesh
                    geometry={nodes.Extrude_1.geometry}
                    material={materials.RootNode_56_}
                    position={[0, 0, 0]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                </group>
              </group>
              <group position={[170.66, -605.61, -229.03]} rotation={[-0.46, -0.27, -1.05]} scale={[1, 1, 1]}>
                <mesh
                  geometry={nodes.Cylinder_5.geometry}
                  material={materials.RootNode_61_}
                  position={[-400.46, 178.49, 501.22]}
                  rotation={[0.02, 0.53, -1.2]}
                />
              </group>
            </group>
            <group position={[-30.77, 41.39, -34.17]} rotation={[1.46, -0.43, 1.56]} scale={[1, 1, 1]}>
              <group position={[2.55, 2.71, -7.63]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 1, 1]}>
                <group position={[0, -0.36, 0]} rotation={[0, 0, 0]}>
                  <group position={[4.08, 0, 0]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
                    <group position={[0.05, -5.81, 0]} rotation={[0.16, 0, Math.PI]} scale={[1, 1, 1]}>
                      <mesh
                        geometry={nodes.Cylindre_8_1.geometry}
                        material={materials.RootNode_66_}
                        position={[0, 0, 0]}
                        rotation={[Math.PI / 2, 0, 0]}
                      />
                      <mesh
                        geometry={nodes.Cylindre_9.geometry}
                        material={materials.RootNode_67_}
                        position={[4.08, 0, 0]}
                        rotation={[Math.PI / 2, 0, 0]}
                      />
                    </group>
                    <mesh
                      geometry={nodes.Cylindre_7_1.geometry}
                      material={materials.RootNode_65_}
                      position={[0, 0, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                  </group>
                  <mesh
                    geometry={nodes.Cylindre_6_1.geometry}
                    material={materials.RootNode_64_}
                    position={[0, 0, 0]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                </group>
              </group>
              <group position={[-0.68, 0.77, 1.04]} rotation={[1.57, 0, 0]} scale={[1, 1, 1]}>
                <mesh
                  geometry={nodes.Cylindre_10.geometry}
                  material={materials.RootNode_68_}
                  position={[0, -9.79, 0]}
                  rotation={[-Math.PI / 2, 0, -Math.PI]}
                />
              </group>
              <group position={[-0.68, 1.36, -4.98]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
                <mesh
                  geometry={nodes.Cube_22.geometry}
                  material={materials.RootNode_70_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
              </group>
              <mesh
                geometry={nodes.Cube_19.geometry}
                material={materials.RootNode_62_}
                position={[2.37, -1.64, -4.97]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                geometry={nodes.Cube_20.geometry}
                material={materials.RootNode_63_}
                position={[2.39, 3.49, -4.99]}
                rotation={[1.57, 0, 0]}
              />
              <mesh
                geometry={nodes.Cube_21.geometry}
                material={materials.RootNode_69_}
                position={[-0.68, 4.76, -1.73]}
                rotation={[Math.PI / 2, 0, 0]}
              />
            </group>
            <group position={[6.05, 27.14, 3.33]} rotation={[3.08, 0.02, -2.51]} scale={[1, 1, 1]}>
              <group position={[0, -0.1, 0]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
                <group position={[-0.05, -0.76, -0.18]} rotation={[0, 0, -Math.PI]} scale={[1, 1, 1]}>
                  <mesh
                    geometry={nodes.Cube_23.geometry}
                    material={materials._6___Default}
                    position={[-0.09, -0.13, 0.09]}
                    rotation={[Math.PI / 2, 0, -Math.PI]}
                  />
                  <mesh
                    geometry={nodes.Cube_24.geometry}
                    material={materials.RootNode_75_}
                    position={[-0.09, -0.13, 0.09]}
                    rotation={[Math.PI / 2, 0, -Math.PI]}
                  />
                  <mesh
                    geometry={nodes.Cube_25.geometry}
                    material={materials.RootNode_76_}
                    position={[-0.09, -0.13, 0.09]}
                    rotation={[Math.PI / 2, 0, -Math.PI]}
                  />
                  <mesh
                    geometry={nodes.Cylinder_6.geometry}
                    material={materials.RootNode_73_}
                    position={[-1.25, 1.21, -1.63]}
                    rotation={[0, 0, 0]}
                  />
                </group>
                <mesh
                  geometry={nodes.insect_1.geometry}
                  material={materials.RootNode_71_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.lap.geometry}
                  material={materials.RootNode_78_}
                  position={[0.57, 0.08, 0.08]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.st.geometry}
                  material={materials.RootNode_77_}
                  position={[0, -0.2, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.wire.geometry}
                  material={materials.RootNode_72_}
                  position={[-0.23, -0.03, 0.82]}
                  rotation={[1.74, 0, 0]}
                />
              </group>
            </group>
            <group position={[4.35, 25.76, -8.43]} rotation={[-1.63, 0.32, 1.56]} scale={[1, 1, 1]}>
              <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
                <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
                  <mesh
                    geometry={nodes.Zylinder_2_1.geometry}
                    material={materials.RootNode_82_}
                    position={[0, 0, 0]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                  <mesh
                    geometry={nodes.Zylinder_3.geometry}
                    material={materials.RootNode_83_}
                    position={[-3.9, 0, 0]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                </group>
                <mesh
                  geometry={nodes.Zylinder_1.geometry}
                  material={materials.RootNode_81_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
              </group>
              <mesh
                geometry={nodes.W_rfel_1.geometry}
                material={materials.RootNode_80_}
                position={[0, 0, 0]}
                rotation={[Math.PI / 2, 0, 0]}
              />
            </group>
            <group position={[-25.64, 14.66, -0.84]} rotation={[-0.07, -0.02, 1.78]} scale={[1, 1, 1]}>
              <group position={[0.95, -0.66, 0]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
                <mesh
                  geometry={nodes.Cube_26.geometry}
                  material={materials.RootNode_84_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
              </group>
              <mesh
                geometry={nodes.Cube_27.geometry}
                material={materials.RootNode_85_}
                position={[-1.9, 1.31, 0]}
                rotation={[Math.PI / 2, 0, 0]}
              />
            </group>
            <group position={[-5.71, 9.99, -37.9]} rotation={[-0.07, -0.02, -1.94]} scale={[1, 1, 1]}>
              <group position={[0.22, -0.44, 39.66]} rotation={[-1.57, -1.51, 0]} scale={[1, 1, 1]}>
                <group position={[-0.49, -6.75, 16.76]} rotation={[1.57, 0, 0]} scale={[1, 1, 1]}>
                  <group position={[1.31, 0.07, 0]} rotation={[0, 0, -0.03]} scale={[1, 1, 1]}>
                    <mesh
                      geometry={nodes.Cube_30.geometry}
                      material={materials.RootNode_89_}
                      position={[-0.09, 0.09, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                    <mesh
                      geometry={nodes.Cube_31.geometry}
                      material={materials.RootNode_90_}
                      position={[-0.48, -0.03, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                    <mesh
                      geometry={nodes.Cube_32.geometry}
                      material={materials.RootNode_91_}
                      position={[0.57, -0.06, 0]}
                      rotation={[Math.PI / 2, 0, -Math.PI]}
                    />
                  </group>
                  <group position={[-1.43, -0.07, 0]} rotation={[0, 0, 0.09]} scale={[1, 1, 1]}>
                    <mesh
                      geometry={nodes.Cube_33.geometry}
                      material={materials.RootNode_92_}
                      position={[0.03, 0.02, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                    <mesh
                      geometry={nodes.Cube_34.geometry}
                      material={materials.RootNode_93_}
                      position={[-0.03, -0.02, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                  </group>
                  <mesh
                    geometry={nodes.Cube_28.geometry}
                    material={materials.RootNode_87_}
                    position={[0.07, -0.08, 0.43]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                  <mesh
                    geometry={nodes.Cube_29.geometry}
                    material={materials.RootNode_88_}
                    position={[0.07, -0.08, -0.44]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                </group>
                <group position={[-0.49, 11.91, 16.76]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1, 1]}>
                  <group position={[1.31, 0.07, 0]} rotation={[0, 0, -0.03]} scale={[1, 1, 1]}>
                    <mesh
                      geometry={nodes.Cube_37.geometry}
                      material={materials.RootNode_96_}
                      position={[-0.09, 0.09, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                    <mesh
                      geometry={nodes.Cube_38.geometry}
                      material={materials.RootNode_97_}
                      position={[-0.48, -0.03, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                    <mesh
                      geometry={nodes.Cube_39.geometry}
                      material={materials.RootNode_98_}
                      position={[0.57, -0.06, 0]}
                      rotation={[Math.PI / 2, 0, -Math.PI]}
                    />
                  </group>
                  <group position={[-1.43, -0.07, 0]} rotation={[0, 0, 0.09]} scale={[1, 1, 1]}>
                    <mesh
                      geometry={nodes.Cube_40.geometry}
                      material={materials.RootNode_99_}
                      position={[0.03, 0.02, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                    <mesh
                      geometry={nodes.Cube_41.geometry}
                      material={materials.RootNode_100_}
                      position={[-0.03, -0.02, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                  </group>
                  <mesh
                    geometry={nodes.Cube_35.geometry}
                    material={materials.RootNode_94_}
                    position={[0.07, -0.08, 0.44]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                  <mesh
                    geometry={nodes.Cube_36.geometry}
                    material={materials.RootNode_95_}
                    position={[0.07, -0.08, -0.44]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                </group>
              </group>
              <group position={[0.22, -0.44, 39.66]} rotation={[Math.PI / 2, -0.21, -Math.PI]} scale={[1, 1, 1]}>
                <group position={[-0.49, -6.75, 16.76]} rotation={[1.57, 0, 0]} scale={[1, 1, 1]}>
                  <group position={[1.31, 0.07, 0]} rotation={[0, 0, -0.03]} scale={[1, 1, 1]}>
                    <mesh
                      geometry={nodes.Cube_44.geometry}
                      material={materials.RootNode_103_}
                      position={[-0.09, 0.09, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                    <mesh
                      geometry={nodes.Cube_45.geometry}
                      material={materials.RootNode_104_}
                      position={[-0.48, -0.03, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                    <mesh
                      geometry={nodes.Cube_46.geometry}
                      material={materials.RootNode_105_}
                      position={[0.57, -0.06, 0]}
                      rotation={[Math.PI / 2, 0, Math.PI]}
                    />
                  </group>
                  <group position={[-1.43, -0.07, 0]} rotation={[0, 0, 0.09]} scale={[1, 1, 1]}>
                    <mesh
                      geometry={nodes.Cube_47.geometry}
                      material={materials.RootNode_106_}
                      position={[0.03, 0.02, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                    <mesh
                      geometry={nodes.Cube_48.geometry}
                      material={materials.RootNode_107_}
                      position={[-0.03, -0.02, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                  </group>
                  <mesh
                    geometry={nodes.Cube_42.geometry}
                    material={materials.RootNode_101_}
                    position={[0.07, -0.08, 0.43]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                  <mesh
                    geometry={nodes.Cube_43.geometry}
                    material={materials.RootNode_102_}
                    position={[0.07, -0.08, -0.44]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                </group>
                <group position={[-0.49, 11.91, 16.76]} rotation={[1.57, 0, 0]} scale={[1, 1, 1]}>
                  <group position={[1.31, 0.07, 0]} rotation={[0, 0, -0.03]} scale={[1, 1, 1]}>
                    <mesh
                      geometry={nodes.Cube_51.geometry}
                      material={materials.RootNode_110_}
                      position={[-0.09, 0.09, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                    <mesh
                      geometry={nodes.Cube_52.geometry}
                      material={materials.RootNode_111_}
                      position={[-0.48, -0.03, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                    <mesh
                      geometry={nodes.Cube_53.geometry}
                      material={materials.RootNode_112_}
                      position={[0.57, -0.06, 0]}
                      rotation={[Math.PI / 2, 0, Math.PI]}
                    />
                  </group>
                  <group position={[-1.43, -0.07, 0]} rotation={[0, 0, 0.09]} scale={[1, 1, 1]}>
                    <mesh
                      geometry={nodes.Cube_54.geometry}
                      material={materials.RootNode_113_}
                      position={[0.03, 0.02, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                    <mesh
                      geometry={nodes.Cube_55.geometry}
                      material={materials.RootNode_114_}
                      position={[-0.03, -0.02, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                  </group>
                  <mesh
                    geometry={nodes.Cube_49.geometry}
                    material={materials.RootNode_108_}
                    position={[0.07, -0.08, 0.44]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                  <mesh
                    geometry={nodes.Cube_50.geometry}
                    material={materials.RootNode_109_}
                    position={[0.07, -0.08, -0.44]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                </group>
              </group>
              <group position={[496.15, -228.91, -677.62]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
                <mesh
                  geometry={nodes.Cylinder_9.geometry}
                  material={materials.RootNode_115_}
                  position={[-495.93, 228.47, 717.28]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
              </group>
              <group position={[0.22, -0.44, 53.1]} rotation={[-1.57, 0, 0]}>
                <mesh
                  geometry={nodes.Cylinder_11.geometry}
                  material={materials.RootNode_117_}
                  position={[0, -0.71, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.Cylinder_12.geometry}
                  material={materials.RootNode_118_}
                  position={[0, 0.71, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
              </group>
              <group position={[0.22, -0.44, 19.07]} rotation={[-1.57, 0, 0]} scale={[1, 1, 1]}>
                <mesh
                  geometry={nodes.Cylinder_13.geometry}
                  material={materials.RootNode_119_}
                  position={[0, -0.71, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.Cylinder_14.geometry}
                  material={materials.RootNode_120_}
                  position={[0, 0.71, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
              </group>
              <mesh
                geometry={nodes.Cylinder_10.geometry}
                material={materials.RootNode_116_}
                position={[0.22, -0.44, 51.56]}
                rotation={[0, 0, 0]}
              />
              <mesh
                geometry={nodes.Cylinder_8.geometry}
                material={materials.RootNode_86_}
                position={[0.22, -0.44, 39.66]}
                rotation={[0, 0, 0]}
              />
            </group>
            <group position={[-4.55, -4.9, -16.31]} rotation={[-2.79, 0.24, 2.03]} scale={[1, 1, 1]}>
              <group position={[16.25, 19.66, -14.03]} rotation={[0.26, 0.67, -0.82]} scale={[1, 1, 1]}>
                <mesh
                  geometry={nodes.Cylinder_15.geometry}
                  material={materials.RootNode_122_}
                  position={[0.27, -27.2, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.Cylinder_16.geometry}
                  material={materials.RootNode_123_}
                  position={[0.27, -11.78, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.Cylinder_17.geometry}
                  material={materials.RootNode_124_}
                  position={[-1.07, 8.66, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.Cylinder_18.geometry}
                  material={materials.RootNode_125_}
                  position={[0.27, 3.13, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.Cylinder_19.geometry}
                  material={materials.RootNode_126_}
                  position={[0.27, 2.91, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
              </group>
              <group position={[-14.32, -21.37, 1.23]} rotation={[-2.86, -0.68, 0.83]} scale={[1, 1, 1]}>
                <mesh
                  geometry={nodes.Cylinder_20.geometry}
                  material={materials.RootNode_127_}
                  position={[0.27, -13.93, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.Cylinder_21.geometry}
                  material={materials.RootNode_128_}
                  position={[0.27, -8.71, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.Cylinder_22.geometry}
                  material={materials.RootNode_129_}
                  position={[-1.07, 13.87, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.Cylinder_23.geometry}
                  material={materials.RootNode_130_}
                  position={[0.27, 3.13, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.Cylinder_24.geometry}
                  material={materials.RootNode_131_}
                  position={[0.27, 4.72, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
              </group>
              <group position={[-86.97, -122.53, 34.48]} rotation={[-3.09, -0.49, 2.27]} scale={[1, 1, 1]}>
                <group position={[-76.54, 0.28, 0]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
                  <mesh
                    geometry={nodes.Cube_56.geometry}
                    material={materials.RootNode_133_}
                    position={[-0.02, 0.7, 0]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                  <mesh
                    geometry={nodes.Cube_57.geometry}
                    material={materials.RootNode_134_}
                    position={[0.02, -0.7, 0]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                </group>
                <group position={[-36.69, 0.28, 0]} rotation={[0, 0, -0.14]} scale={[1, 1, 1]}>
                  <group position={[111.29, -17.95, 0]} rotation={[0, 0, -0.16]} scale={1}>
                    <mesh
                      geometry={nodes.Cube_58.geometry}
                      material={materials.RootNode_136_}
                      position={[-1.14, 12.19, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                    <mesh
                      geometry={nodes.Cube_59.geometry}
                      material={materials.RootNode_137_}
                      position={[-1.1, 10.8, 0]}
                      rotation={[Math.PI / 2, 0, 0]}
                    />
                  </group>
                  <mesh
                    geometry={nodes.Cube_60.geometry}
                    material={materials.RootNode_138_}
                    position={[36.49, 0.7, 0]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                  <mesh
                    geometry={nodes.Cube_61.geometry}
                    material={materials.RootNode_139_}
                    position={[36.53, -0.7, 0]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                  <mesh
                    geometry={nodes.Cylinder_26.geometry}
                    material={materials.RootNode_135_}
                    position={[74.87, -1.14, 0]}
                    rotation={[Math.PI / 2, -0.16, 0]}
                  />
                </group>
                <mesh
                  geometry={nodes.Cylinder_25.geometry}
                  material={materials.RootNode_132_}
                  position={[-37.85, -0.42, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
              </group>
              <group position={[87.71, 114.36, -46]} rotation={[-3.09, -0.49, 2.27]} scale={[1, 1, 1]}>
                <group position={[76.04, 0.28, 0]} rotation={[0, 0, 0]} scale={[1, 1, 1]}>
                  <mesh
                    geometry={nodes.Cube_62.geometry}
                    material={materials.RootNode_140_}
                    position={[-0.02, 0.7, 0]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                  <mesh
                    geometry={nodes.Cube_63.geometry}
                    material={materials.RootNode_141_}
                    position={[0.02, -0.7, 0]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                </group>
                <group position={[-39.35, 14.43, 0]} rotation={[0, 0, 0.09]} scale={[1, 1, 1]}>
                  <mesh
                    geometry={nodes.Cube_64.geometry}
                    material={materials.RootNode_144_}
                    position={[-35.76, -0.12, 0]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                  <mesh
                    geometry={nodes.Cube_65.geometry}
                    material={materials.RootNode_145_}
                    position={[-35.72, -1.52, 0]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                </group>
                <group position={[35.79, 0.28, 0]} rotation={[0, 0, -0.19]} scale={[1, 1, 1]}>
                  <mesh
                    geometry={nodes.Cube_66.geometry}
                    material={materials.RootNode_146_}
                    position={[-35.99, 0.7, 0]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                  <mesh
                    geometry={nodes.Cube_67.geometry}
                    material={materials.RootNode_147_}
                    position={[-35.95, -0.7, 0]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                </group>
                <mesh
                  geometry={nodes.Cylinder_27.geometry}
                  material={materials.RootNode_142_}
                  position={[38.53, -0.42, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.Cylinder_28.geometry}
                  material={materials.RootNode_143_}
                  position={[-36.41, 12.92, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
              </group>
              <group
                name="cassini_orbitter"
                position={[-2.67, 9.89, 24.33]}
                rotation={[Math.PI, -0.48, 0.14]}
                scale={[1, 1, 1]}>
                <mesh
                  geometry={nodes.boot9.geometry}
                  material={materials.RootNode_152_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes['default'].geometry}
                  material={materials.RootNode_189_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.hga1_ant.geometry}
                  material={materials.RootNode_151_}
                  position={[0, 0, 0.23]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.hga1_ant_brace.geometry}
                  material={materials.RootNode_150_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.lrg_tank.geometry}
                  material={materials.RootNode_188_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.magb_2.geometry}
                  material={materials.RootNode_165_}
                  position={[0.19, 0.81, 0.38]}
                  rotation={[Math.PI / 2, 0.78, 0]}
                />
                <mesh
                  geometry={nodes.obj1.geometry}
                  material={materials.RootNode_153_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.obj1_3.geometry}
                  material={materials.RootNode_160_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.obj1_4.geometry}
                  material={materials.RootNode_163_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.obj1_5.geometry}
                  material={materials.RootNode_149_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.obj1_pm_tank.geometry}
                  material={materials.RootNode_154_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.obj1_pm_thrusters.geometry}
                  material={materials.RootNode_156_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.obj1_pm_thrusters_pm_tsprt.geometry}
                  material={materials.RootNode_155_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.obj1_pm_tsprt.geometry}
                  material={materials.RootNode_157_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.obj1_rtg_hga.geometry}
                  material={materials.RootNode_162_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.obj1_rtgs.geometry}
                  material={materials.RootNode_161_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.revlv.geometry}
                  material={materials.RootNode_159_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.revlv1.geometry}
                  material={materials.RootNode_158_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.sci10_2.geometry}
                  material={materials.RootNode_181_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.sci11_2.geometry}
                  material={materials.RootNode_180_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.sci12_2.geometry}
                  material={materials.RootNode_179_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.sci13.geometry}
                  material={materials.RootNode_164_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.sci13_2.geometry}
                  material={materials.RootNode_178_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.sci14_2.geometry}
                  material={materials.RootNode_177_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.sci17_2.geometry}
                  material={materials.RootNode_176_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.sci18_2.geometry}
                  material={materials.RootNode_175_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.sci19_2.geometry}
                  material={materials.RootNode_174_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.sci20_2.geometry}
                  material={materials.RootNode_173_}
                  position={[-45.95, -27.38, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.sci21_2.geometry}
                  material={materials.RootNode_172_}
                  position={[-45.95, -27.38, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.sci22_2.geometry}
                  material={materials.RootNode_171_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.sci23_2.geometry}
                  material={materials.RootNode_170_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.sci24_2.geometry}
                  material={materials.RootNode_169_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.sci25_2.geometry}
                  material={materials.RootNode_168_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.sci28_2.geometry}
                  material={materials.RootNode_167_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.sci29_2.geometry}
                  material={materials.RootNode_166_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.sci2_2.geometry}
                  material={materials.RootNode_187_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.sci3_2.geometry}
                  material={materials.RootNode_186_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.sci4_2.geometry}
                  material={materials.RootNode_185_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.sci6_2.geometry}
                  material={materials.RootNode_184_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.sci8_2.geometry}
                  material={materials.RootNode_183_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.sci9_2.geometry}
                  material={materials.RootNode_182_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  geometry={nodes.small_tank.geometry}
                  material={materials.RootNode_148_}
                  position={[0, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
              </group>
            </group>
            <mesh
              geometry={nodes.Cylinder_7.geometry}
              material={materials.RootNode_79_}
              position={[-5.78, 8.68, -60.44]}
              rotation={[3.09, 0.01, 1.99]}
            />
            <mesh
              geometry={nodes.obj1_2.geometry}
              material={materials.RootNode_121_}
              position={[-6.21, 10.18, -37.92]}
              rotation={[-1.69, -1.2, 3.09]}
            />
          </group>
          <mesh
            geometry={nodes.Plane.geometry}
            material={materials.RootNode}
            position={[1030.01, 531.57, -414.5]}
            rotation={[-2.21, 0.9, -1.05]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/blender_sat.glb')
