/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/float.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(()=>{
    actions['Armature|mixamo.com|Layer0.001'].play()
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Armature" rotation={[Math.PI / 2, 0 , (6*Math.PI)/4 + 0.5]} scale={[0.4, 0.4, 0.4]}>
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh
          geometry={nodes.Ch03.geometry}
          material={materials['Ch03_Body.001']}
          skeleton={nodes.Ch03.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/float.glb')
