/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/jonah_web.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(()=>{
    // // Key.001|CC3_Base_Plus_TempMotion|CC3_Base_Plus_TempMotion
    console.log(actions)
    // actions['Armature|CC3_Base_Plus_TempMotion|CC3_Base_Plus_TempMotion'].play()
    // actions['Key.001|CC3_Base_Plus_TempMotion|CC3_Base_Plus_TempMotion'].play()
    // actions['Key.002|CC3_Base_Plus_TempMotion|CC3_Base_Plus_TempMotion'].play()
    // actions['Key.003|CC3_Base_Plus_TempMotion|CC3_Base_Plus_TempMotion'].play()
    // actions['Key.004|CC3_Base_Plus_TempMotion|CC3_Base_Plus_TempMotion'].play()
    // actions['Key|CC3_Base_Plus_TempMotion|CC3_Base_Plus_TempMotion'].play()

  })

  return (
    <group ref={group} {...props} dispose={null} rotation={[0, Math.PI / 2 -0.5 , 0 ]} scale={[1, 1, 1]}>
      <mesh
        geometry={nodes.CC_Base_Tongue.geometry}
        material={materials.aiStandardSurface21}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.CC_Base_Body_1.geometry} material={materials.aiStandardSurface8} />
        <mesh geometry={nodes.CC_Base_Body_2.geometry} material={materials.aiStandardSurface9} />
        <mesh geometry={nodes.CC_Base_Body_3.geometry} material={materials.aiStandardSurface10} />
        <mesh geometry={nodes.CC_Base_Body_4.geometry} material={materials.aiStandardSurface7} />
        <mesh geometry={nodes.CC_Base_Body_5.geometry} material={materials.aiStandardSurface6} />
        <mesh geometry={nodes.CC_Base_Body_6.geometry} material={materials.aiStandardSurface5} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.CC_Base_Eye_1.geometry} material={materials.aiStandardSurface11} />
        <mesh geometry={nodes.CC_Base_Eye_2.geometry} material={materials.aiStandardSurface14} />
        <mesh geometry={nodes.CC_Base_Eye_3.geometry} material={materials.aiStandardSurface12} />
        <mesh geometry={nodes.CC_Base_Eye_4.geometry} material={materials.aiStandardSurface13} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.CC_Base_Teeth_1.geometry} material={materials.aiStandardSurface15} />
        <mesh geometry={nodes.CC_Base_Teeth_2.geometry} material={materials.aiStandardSurface16} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.CC_Base_EyeOcclusion_1.geometry} material={materials.aiStandardSurface18} />
        <mesh geometry={nodes.CC_Base_EyeOcclusion_2.geometry} material={materials.aiStandardSurface17} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.CC_Base_TearLine_1.geometry} material={materials.aiStandardSurface19} />
        <mesh geometry={nodes.CC_Base_TearLine_2.geometry} material={materials.aiStandardSurface20} />
      </group>
      <mesh
        geometry={nodes.Sideburns_Narrow.geometry}
        material={materials.aiStandardSurface22}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plaid_Punk_Shirt.geometry}
        material={materials.aiStandardSurface1}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1.01, 1.01, 1.01]}
      />
      <mesh geometry={nodes.Jeans.geometry} material={materials.aiStandardSurface2} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Boots.geometry} material={materials.aiStandardSurface4} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh
        geometry={nodes.thrasher_cap_1.geometry}
        material={nodes.thrasher_cap_1.material}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.thrasher_cap_2.geometry}
        material={nodes.thrasher_cap_2.material}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.thrasher_cap_3.geometry}
        material={nodes.thrasher_cap_3.material}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="thrasher_cap_4"
        geometry={nodes.thrasher_cap_4.geometry}
        material={nodes.thrasher_cap_4.material}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/jonah_web.glb')
