/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/me2.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(()=>{
    // Key.001|CC3_Base_Plus_TempMotion|CC3_Base_Plus_TempMotion
    actions['Armature|CC3_Base_Plus_TempMotion|CC3_Base_Plus_TempMotion'].play()
    actions['Key.001|CC3_Base_Plus_TempMotion|CC3_Base_Plus_TempMotion'].play()
    actions['Key.002|CC3_Base_Plus_TempMotion|CC3_Base_Plus_TempMotion'].play()
    actions['Key.003|CC3_Base_Plus_TempMotion|CC3_Base_Plus_TempMotion'].play()
    actions['Key.004|CC3_Base_Plus_TempMotion|CC3_Base_Plus_TempMotion'].play()
    actions['Key|CC3_Base_Plus_TempMotion|CC3_Base_Plus_TempMotion'].play()

  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Armature" rotation={[0, Math.PI / 2 -0.5 , 0 ]} scale={[0.4, 0.4, 0.4]}>
        <primitive object={nodes.BoneRoot} />
        <skinnedMesh geometry={nodes.Boots.geometry} material={materials.Boots} skeleton={nodes.Boots.skeleton} />
        <skinnedMesh geometry={nodes.Boxers.geometry} material={materials.Boxers} skeleton={nodes.Boxers.skeleton} />
        <skinnedMesh
          geometry={nodes.CC_Base_Eye_1.geometry}
          material={materials.Std_Eye_R}
          skeleton={nodes.CC_Base_Eye_1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.CC_Base_Eye_2.geometry}
          material={materials.Std_Cornea_R}
          skeleton={nodes.CC_Base_Eye_2.skeleton}
        />
        <skinnedMesh
          geometry={nodes.CC_Base_Eye_3.geometry}
          material={materials.Std_Eye_L}
          skeleton={nodes.CC_Base_Eye_3.skeleton}
        />
        <skinnedMesh
          geometry={nodes.CC_Base_Eye_4.geometry}
          material={materials.Std_Cornea_L}
          skeleton={nodes.CC_Base_Eye_4.skeleton}
        />
        <skinnedMesh
          geometry={nodes.CC_Base_Teeth_1.geometry}
          material={materials.Std_Upper_Teeth}
          skeleton={nodes.CC_Base_Teeth_1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.CC_Base_Teeth_2.geometry}
          material={materials.Std_Lower_Teeth}
          skeleton={nodes.CC_Base_Teeth_2.skeleton}
        />
        <skinnedMesh geometry={nodes.Jeans.geometry} material={materials.Jeans} skeleton={nodes.Jeans.skeleton} />
        <skinnedMesh
          geometry={nodes.Plaid_Punk_Shirt.geometry}
          material={materials.Plaid_Punk_Shirt}
          skeleton={nodes.Plaid_Punk_Shirt.skeleton}
        />
        <skinnedMesh
          geometry={nodes.thrasher_cap_001_1.geometry}
          material={nodes.thrasher_cap_001_1.material}
          skeleton={nodes.thrasher_cap_001_1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.thrasher_cap_002_1.geometry}
          material={nodes.thrasher_cap_002_1.material}
          skeleton={nodes.thrasher_cap_002_1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.thrasher_cap_003_1.geometry}
          material={nodes.thrasher_cap_003_1.material}
          skeleton={nodes.thrasher_cap_003_1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.thrasher_cap_004_1.geometry}
          material={nodes.thrasher_cap_004_1.material}
          skeleton={nodes.thrasher_cap_004_1.skeleton}
        />
        <skinnedMesh
          name="CC_Base_Body_1"
          geometry={nodes.CC_Base_Body_1.geometry}
          material={materials.Std_Skin_Head}
          skeleton={nodes.CC_Base_Body_1.skeleton}
          morphTargetDictionary={nodes.CC_Base_Body_1.morphTargetDictionary}
          morphTargetInfluences={nodes.CC_Base_Body_1.morphTargetInfluences}
        />
        <skinnedMesh
          name="CC_Base_Body_2"
          geometry={nodes.CC_Base_Body_2.geometry}
          material={materials.Std_Skin_Body}
          skeleton={nodes.CC_Base_Body_2.skeleton}
          morphTargetDictionary={nodes.CC_Base_Body_2.morphTargetDictionary}
          morphTargetInfluences={nodes.CC_Base_Body_2.morphTargetInfluences}
        />
        <skinnedMesh
          name="CC_Base_Body_3"
          geometry={nodes.CC_Base_Body_3.geometry}
          material={materials.Std_Skin_Arm}
          skeleton={nodes.CC_Base_Body_3.skeleton}
          morphTargetDictionary={nodes.CC_Base_Body_3.morphTargetDictionary}
          morphTargetInfluences={nodes.CC_Base_Body_3.morphTargetInfluences}
        />
        <skinnedMesh
          name="CC_Base_Body_4"
          geometry={nodes.CC_Base_Body_4.geometry}
          material={materials.Std_Skin_Leg}
          skeleton={nodes.CC_Base_Body_4.skeleton}
          morphTargetDictionary={nodes.CC_Base_Body_4.morphTargetDictionary}
          morphTargetInfluences={nodes.CC_Base_Body_4.morphTargetInfluences}
        />
        <skinnedMesh
          name="CC_Base_Body_5"
          geometry={nodes.CC_Base_Body_5.geometry}
          material={materials.Std_Nails}
          skeleton={nodes.CC_Base_Body_5.skeleton}
          morphTargetDictionary={nodes.CC_Base_Body_5.morphTargetDictionary}
          morphTargetInfluences={nodes.CC_Base_Body_5.morphTargetInfluences}
        />
        <skinnedMesh
          name="CC_Base_Body_6"
          geometry={nodes.CC_Base_Body_6.geometry}
          material={materials.Std_Eyelash}
          skeleton={nodes.CC_Base_Body_6.skeleton}
          morphTargetDictionary={nodes.CC_Base_Body_6.morphTargetDictionary}
          morphTargetInfluences={nodes.CC_Base_Body_6.morphTargetInfluences}
        />
        <skinnedMesh
          name="Sideburns_Narrow"
          geometry={nodes.Sideburns_Narrow.geometry}
          material={materials.Beard}
          skeleton={nodes.Sideburns_Narrow.skeleton}
          morphTargetDictionary={nodes.Sideburns_Narrow.morphTargetDictionary}
          morphTargetInfluences={nodes.Sideburns_Narrow.morphTargetInfluences}
        />
        <skinnedMesh
          name="CC_Base_TearLine_1"
          geometry={nodes.CC_Base_TearLine_1.geometry}
          material={materials.Std_Tearline_R}
          skeleton={nodes.CC_Base_TearLine_1.skeleton}
          morphTargetDictionary={nodes.CC_Base_TearLine_1.morphTargetDictionary}
          morphTargetInfluences={nodes.CC_Base_TearLine_1.morphTargetInfluences}
        />
        <skinnedMesh
          name="CC_Base_TearLine_2"
          geometry={nodes.CC_Base_TearLine_2.geometry}
          material={materials.Std_Tearline_L}
          skeleton={nodes.CC_Base_TearLine_2.skeleton}
          morphTargetDictionary={nodes.CC_Base_TearLine_2.morphTargetDictionary}
          morphTargetInfluences={nodes.CC_Base_TearLine_2.morphTargetInfluences}
        />
        <skinnedMesh
          name="CC_Base_Tongue"
          geometry={nodes.CC_Base_Tongue.geometry}
          material={materials.Std_Tongue}
          skeleton={nodes.CC_Base_Tongue.skeleton}
          morphTargetDictionary={nodes.CC_Base_Tongue.morphTargetDictionary}
          morphTargetInfluences={nodes.CC_Base_Tongue.morphTargetInfluences}
        />
        <skinnedMesh
          name="CC_Base_EyeOcclusion_1"
          geometry={nodes.CC_Base_EyeOcclusion_1.geometry}
          material={materials.Std_Eye_Occlusion_R}
          skeleton={nodes.CC_Base_EyeOcclusion_1.skeleton}
          morphTargetDictionary={nodes.CC_Base_EyeOcclusion_1.morphTargetDictionary}
          morphTargetInfluences={nodes.CC_Base_EyeOcclusion_1.morphTargetInfluences}
        />
        <skinnedMesh
          name="CC_Base_EyeOcclusion_2"
          geometry={nodes.CC_Base_EyeOcclusion_2.geometry}
          material={materials.Std_Eye_Occlusion_L}
          skeleton={nodes.CC_Base_EyeOcclusion_2.skeleton}
          morphTargetDictionary={nodes.CC_Base_EyeOcclusion_2.morphTargetDictionary}
          morphTargetInfluences={nodes.CC_Base_EyeOcclusion_2.morphTargetInfluences}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/me2.glb')
